/// AUTO-GENERATED by beacon/build — do not edit manually.
/// Re-run `gleam run -m beacon/build` to regenerate.

import spreadsheet
import gleam/json
import gleam/dynamic/decode

fn encode_cell(s: spreadsheet.Cell) -> json.Json {
  json.object([
    #("row", json.int(s.row)),
    #("col", json.int(s.col)),
    #("value", json.string(s.value)),
  ])
}



fn server_decode_cell() -> decode.Decoder(spreadsheet.Cell) {
  use row <- decode.field("row", decode.int)
  use col <- decode.field("col", decode.int)
  use value <- decode.field("value", decode.string)
  decode.success(spreadsheet.Cell(row: row, col: col, value: value))
}



/// Encode the Model to JSON for model_sync.
pub fn encode_model(state: #(spreadsheet.Model, spreadsheet.Local)) -> String {
  let model = state.0
  let local = state.1
  json.object([
    #("cells", json.array(model.cells, encode_cell)),
    #("selected_row", json.int(model.selected_row)),
    #("selected_col", json.int(model.selected_col)),
    #("editing", json.bool(model.editing)),
    #("edit_buffer", json.string(model.edit_buffer)),
  ])
  |> json.to_string
}

/// Decode a #(Model, Local) from JSON string (for applying client patches).
pub fn decode_model(json_str: String) -> Result(#(spreadsheet.Model, spreadsheet.Local), String) {
  let state_decoder = {
    use cells <- decode.field("cells", decode.list(server_decode_cell()))
    use selected_row <- decode.field("selected_row", decode.int)
    use selected_col <- decode.field("selected_col", decode.int)
    use editing <- decode.field("editing", decode.bool)
    use edit_buffer <- decode.field("edit_buffer", decode.string)

    decode.success(#(spreadsheet.Model(cells: cells, selected_row: selected_row, selected_col: selected_col, editing: editing, edit_buffer: edit_buffer), spreadsheet.Local))
  }
  case json.parse(json_str, state_decoder) {
    Ok(state) -> Ok(state)
    Error(_) -> Error("Failed to decode model+local")
  }
}

pub fn encode_substate_cells(state: #(spreadsheet.Model, spreadsheet.Local)) -> String {
  let model = state.0
  json.array(model.cells, encode_cell)
  |> json.to_string
}

pub fn substate_names() -> List(String) {
  ["cells"]
}

pub fn encode_flat_fields(state: #(spreadsheet.Model, spreadsheet.Local)) -> String {
  let model = state.0
  json.object([
    #("selected_row", json.int(model.selected_row)),
    #("selected_col", json.int(model.selected_col)),
    #("editing", json.bool(model.editing)),
    #("edit_buffer", json.string(model.edit_buffer)),
  ])
  |> json.to_string
}
