/// AUTO-GENERATED by beacon/build — do not edit manually.
/// Re-run `gleam run -m beacon/build` to regenerate.

import spreadsheet
import beacon/element
import gleam/json
import gleam/dynamic/decode

fn encode_cell(s: spreadsheet.Cell) -> json.Json {
  json.object([
    #("row", json.int(s.row)),
    #("col", json.int(s.col)),
    #("value", json.string(s.value)),
  ])
}



fn server_decode_cell() -> decode.Decoder(spreadsheet.Cell) {
  use row <- decode.field("row", decode.int)
  use col <- decode.field("col", decode.int)
  use value <- decode.field("value", decode.string)
  decode.success(spreadsheet.Cell(row: row, col: col, value: value))
}



/// Encode the Model to JSON for model_sync.
pub fn encode_model(state: #(spreadsheet.Model, spreadsheet.Local, Nil)) -> String {
  let model = state.0
  json.object([
    #("cells", json.array(model.cells, encode_cell)),
    #("selected_row", json.int(model.selected_row)),
    #("selected_col", json.int(model.selected_col)),
    #("editing", json.bool(model.editing)),
    #("edit_buffer", json.string(model.edit_buffer)),
  ])
  |> json.to_string
}

/// Render the model with the same generated server contract used for SSR.
pub fn render_model(state: #(spreadsheet.Model, spreadsheet.Local, Nil)) -> String {
  let model = state.0
  let local = state.1
  spreadsheet.view(model, local)
  |> element.to_string
}

/// Decode a #(Model, Local, Server) from JSON string (for applying client patches).
pub fn decode_model(json_str: String) -> Result(#(spreadsheet.Model, spreadsheet.Local, Nil), String) {
  let state_decoder = {
    use cells <- decode.field("cells", decode.list(server_decode_cell()))
    use selected_row <- decode.field("selected_row", decode.int)
    use selected_col <- decode.field("selected_col", decode.int)
    use editing <- decode.field("editing", decode.bool)
    use edit_buffer <- decode.field("edit_buffer", decode.string)

    decode.success(#(spreadsheet.Model(cells: cells, selected_row: selected_row, selected_col: selected_col, editing: editing, edit_buffer: edit_buffer), spreadsheet.Local, Nil))
  }
  case json.parse(json_str, state_decoder) {
    Ok(state) -> Ok(state)
    Error(_) -> Error("Failed to decode model+local+server")
  }
}

/// Decode the generated client event contract. Live event decoding never
/// renders the server view or reads the handler registry.
pub fn decode_event(_name: String, _handler_id: String, data: String, _target_path: String) -> Result(spreadsheet.Msg, String) {
  let envelope_decoder = {
    use msg_json <- decode.field("__beacon_msg", decode.string)
    decode.success(msg_json)
  }
  case json.parse(data, envelope_decoder) {
    Ok(msg_json) -> decode_msg(msg_json)
    Error(_) -> Error("Client event missing generated Beacon message envelope")
  }
}


fn decode_msg(json_str: String) -> Result(spreadsheet.Msg, String) {
  let tag_decoder = {
    use tag <- decode.field("tag", decode.string)
    decode.success(tag)
  }
  case json.parse(json_str, tag_decoder) {
    Ok(tag) -> {
      case tag {
    "SelectCell" -> {
      let msg_decoder = {
      use arg0 <- decode.field("arg0", decode.string)
      decode.success(spreadsheet.SelectCell(arg0))
      }
      case json.parse(json_str, msg_decoder) {
        Ok(msg) -> Ok(msg)
        Error(_) -> Error("Generated Beacon message payload did not match tag SelectCell")
      }
    }
    "StartEdit" -> {
      let msg_decoder = {
      decode.success(spreadsheet.StartEdit)
      }
      case json.parse(json_str, msg_decoder) {
        Ok(msg) -> Ok(msg)
        Error(_) -> Error("Generated Beacon message payload did not match tag StartEdit")
      }
    }
    "UpdateBuffer" -> {
      let msg_decoder = {
      use arg0 <- decode.field("arg0", decode.string)
      decode.success(spreadsheet.UpdateBuffer(arg0))
      }
      case json.parse(json_str, msg_decoder) {
        Ok(msg) -> Ok(msg)
        Error(_) -> Error("Generated Beacon message payload did not match tag UpdateBuffer")
      }
    }
    "ConfirmEdit" -> {
      let msg_decoder = {
      use arg0 <- decode.field("arg0", decode.string)
      decode.success(spreadsheet.ConfirmEdit(arg0))
      }
      case json.parse(json_str, msg_decoder) {
        Ok(msg) -> Ok(msg)
        Error(_) -> Error("Generated Beacon message payload did not match tag ConfirmEdit")
      }
    }
    "CancelEdit" -> {
      let msg_decoder = {
      decode.success(spreadsheet.CancelEdit)
      }
      case json.parse(json_str, msg_decoder) {
        Ok(msg) -> Ok(msg)
        Error(_) -> Error("Generated Beacon message payload did not match tag CancelEdit")
      }
    }
    "CellsUpdated" -> {
      let msg_decoder = {
      decode.success(spreadsheet.CellsUpdated)
      }
      case json.parse(json_str, msg_decoder) {
        Ok(msg) -> Ok(msg)
        Error(_) -> Error("Generated Beacon message payload did not match tag CellsUpdated")
      }
    }
    "SetCells" -> {
      let msg_decoder = {
      use arg0 <- decode.field("arg0", decode.list(server_decode_cell()))
      decode.success(spreadsheet.SetCells(arg0))
      }
      case json.parse(json_str, msg_decoder) {
        Ok(msg) -> Ok(msg)
        Error(_) -> Error("Generated Beacon message payload did not match tag SetCells")
      }
    }
        _ -> Error("Unknown generated Beacon message tag " <> tag)
      }
    }
    Error(_) -> Error("Generated Beacon message payload missing tag")
  }
}

pub fn encode_substate_cells(state: #(spreadsheet.Model, spreadsheet.Local, Nil)) -> String {
  let model = state.0
  json.array(model.cells, encode_cell)
  |> json.to_string
}

pub fn substate_names() -> List(String) {
  ["cells"]
}

pub fn encode_flat_fields(state: #(spreadsheet.Model, spreadsheet.Local, Nil)) -> String {
  let model = state.0
  json.object([
    #("selected_row", json.int(model.selected_row)),
    #("selected_col", json.int(model.selected_col)),
    #("editing", json.bool(model.editing)),
    #("edit_buffer", json.string(model.edit_buffer)),
  ])
  |> json.to_string
}
