/// AUTO-GENERATED by beacon/build — do not edit manually.
/// Re-run `gleam run -m beacon/build` to regenerate.

import pong
import beacon/element
import gleam/json
import gleam/dynamic/decode









/// Encode the Model to JSON for model_sync.
pub fn encode_model(state: #(pong.Model, Nil, Nil)) -> String {
  let model = state.0
  json.object([
    #("left_y", json.int(model.left_y)),
    #("right_y", json.int(model.right_y)),
    #("ball_x", json.int(model.ball_x)),
    #("ball_y", json.int(model.ball_y)),
    #("ball_dx", json.int(model.ball_dx)),
    #("ball_dy", json.int(model.ball_dy)),
    #("left_score", json.int(model.left_score)),
    #("right_score", json.int(model.right_score)),
    #("running", json.bool(model.running)),
  ])
  |> json.to_string
}

/// Render the model with the same generated server contract used for SSR.
pub fn render_model(state: #(pong.Model, Nil, Nil)) -> String {
  let model = state.0
  let local = Nil
  pong.view(model, local)
  |> element.to_string
}

/// Decode a #(Model, Local, Server) from JSON string (for applying client patches).
pub fn decode_model(json_str: String) -> Result(#(pong.Model, Nil, Nil), String) {
  let state_decoder = {
    use left_y <- decode.field("left_y", decode.int)
    use right_y <- decode.field("right_y", decode.int)
    use ball_x <- decode.field("ball_x", decode.int)
    use ball_y <- decode.field("ball_y", decode.int)
    use ball_dx <- decode.field("ball_dx", decode.int)
    use ball_dy <- decode.field("ball_dy", decode.int)
    use left_score <- decode.field("left_score", decode.int)
    use right_score <- decode.field("right_score", decode.int)
    use running <- decode.field("running", decode.bool)

    decode.success(#(pong.Model(left_y: left_y, right_y: right_y, ball_x: ball_x, ball_y: ball_y, ball_dx: ball_dx, ball_dy: ball_dy, left_score: left_score, right_score: right_score, running: running), Nil, Nil))
  }
  case json.parse(json_str, state_decoder) {
    Ok(state) -> Ok(state)
    Error(_) -> Error("Failed to decode model+local+server")
  }
}

/// Decode the generated client event contract. Live event decoding never
/// renders the server view or reads the handler registry.
pub fn decode_event(_name: String, _handler_id: String, data: String, _target_path: String) -> Result(pong.Msg, String) {
  let envelope_decoder = {
    use msg_json <- decode.field("__beacon_msg", decode.string)
    decode.success(msg_json)
  }
  case json.parse(data, envelope_decoder) {
    Ok(msg_json) -> decode_msg(msg_json)
    Error(_) -> Error("Client event missing generated Beacon message envelope")
  }
}


fn decode_msg(json_str: String) -> Result(pong.Msg, String) {
  let tag_decoder = {
    use tag <- decode.field("tag", decode.string)
    decode.success(tag)
  }
  case json.parse(json_str, tag_decoder) {
    Ok(tag) -> {
      case tag {
    "LeftUp" -> {
      let msg_decoder = {
      decode.success(pong.LeftUp)
      }
      case json.parse(json_str, msg_decoder) {
        Ok(msg) -> Ok(msg)
        Error(_) -> Error("Generated Beacon message payload did not match tag LeftUp")
      }
    }
    "LeftDown" -> {
      let msg_decoder = {
      decode.success(pong.LeftDown)
      }
      case json.parse(json_str, msg_decoder) {
        Ok(msg) -> Ok(msg)
        Error(_) -> Error("Generated Beacon message payload did not match tag LeftDown")
      }
    }
    "RightUp" -> {
      let msg_decoder = {
      decode.success(pong.RightUp)
      }
      case json.parse(json_str, msg_decoder) {
        Ok(msg) -> Ok(msg)
        Error(_) -> Error("Generated Beacon message payload did not match tag RightUp")
      }
    }
    "RightDown" -> {
      let msg_decoder = {
      decode.success(pong.RightDown)
      }
      case json.parse(json_str, msg_decoder) {
        Ok(msg) -> Ok(msg)
        Error(_) -> Error("Generated Beacon message payload did not match tag RightDown")
      }
    }
    "Tick" -> {
      let msg_decoder = {
      decode.success(pong.Tick)
      }
      case json.parse(json_str, msg_decoder) {
        Ok(msg) -> Ok(msg)
        Error(_) -> Error("Generated Beacon message payload did not match tag Tick")
      }
    }
    "StartGame" -> {
      let msg_decoder = {
      decode.success(pong.StartGame)
      }
      case json.parse(json_str, msg_decoder) {
        Ok(msg) -> Ok(msg)
        Error(_) -> Error("Generated Beacon message payload did not match tag StartGame")
      }
    }
    "PauseGame" -> {
      let msg_decoder = {
      decode.success(pong.PauseGame)
      }
      case json.parse(json_str, msg_decoder) {
        Ok(msg) -> Ok(msg)
        Error(_) -> Error("Generated Beacon message payload did not match tag PauseGame")
      }
    }
        _ -> Error("Unknown generated Beacon message tag " <> tag)
      }
    }
    Error(_) -> Error("Generated Beacon message payload missing tag")
  }
}
