/// AUTO-GENERATED by beacon/build — do not edit manually.
/// Re-run `gleam run -m beacon/build` to regenerate.

import counter
import beacon/element
import gleam/json
import gleam/dynamic/decode









/// Encode the Model to JSON for model_sync.
pub fn encode_model(state: counter.Model) -> String {
  let model = state
  json.object([
    #("count", json.int(model.count)),
  ])
  |> json.to_string
}

/// Render the model with the same generated server contract used for SSR.
pub fn render_model(state: counter.Model) -> String {
  let model = state
  counter.view(model)
  |> element.to_string
}

/// Decode a Model from JSON string (for applying client patches).
pub fn decode_model(json_str: String) -> Result(counter.Model, String) {
  let model_decoder = {
    use count <- decode.field("count", decode.int)
    decode.success(counter.Model(count: count))
  }
  case json.parse(json_str, model_decoder) {
    Ok(model) -> Ok(model)
    Error(_) -> Error("Failed to decode model")
  }
}

/// Decode the generated client event contract. Live event decoding never
/// renders the server view or reads the handler registry.
pub fn decode_event(_name: String, _handler_id: String, data: String, _target_path: String) -> Result(counter.Msg, String) {
  let envelope_decoder = {
    use msg_json <- decode.field("__beacon_msg", decode.string)
    decode.success(msg_json)
  }
  case json.parse(data, envelope_decoder) {
    Ok(msg_json) -> decode_msg(msg_json)
    Error(_) -> Error("Client event missing generated Beacon message envelope")
  }
}


fn decode_msg(json_str: String) -> Result(counter.Msg, String) {
  let tag_decoder = {
    use tag <- decode.field("tag", decode.string)
    decode.success(tag)
  }
  case json.parse(json_str, tag_decoder) {
    Ok(tag) -> {
      case tag {
    "Increment" -> {
      let msg_decoder = {
      decode.success(counter.Increment)
      }
      case json.parse(json_str, msg_decoder) {
        Ok(msg) -> Ok(msg)
        Error(_) -> Error("Generated Beacon message payload did not match tag Increment")
      }
    }
    "Decrement" -> {
      let msg_decoder = {
      decode.success(counter.Decrement)
      }
      case json.parse(json_str, msg_decoder) {
        Ok(msg) -> Ok(msg)
        Error(_) -> Error("Generated Beacon message payload did not match tag Decrement")
      }
    }
        _ -> Error("Unknown generated Beacon message tag " <> tag)
      }
    }
    Error(_) -> Error("Generated Beacon message payload missing tag")
  }
}
