/// AUTO-GENERATED by beacon/build — do not edit manually.
/// Re-run `gleam run -m beacon/build` to regenerate.

import cart
import beacon/element
import gleam/json
import gleam/dynamic/decode

fn encode_product(s: cart.Product) -> json.Json {
  json.object([
    #("id", json.int(s.id)),
    #("name", json.string(s.name)),
    #("price", json.int(s.price)),
    #("stock", json.int(s.stock)),
  ])
}

fn encode_cartitem(s: cart.CartItem) -> json.Json {
  json.object([
    #("product_id", json.int(s.product_id)),
    #("name", json.string(s.name)),
    #("price", json.int(s.price)),
    #("quantity", json.int(s.quantity)),
  ])
}



fn server_decode_product() -> decode.Decoder(cart.Product) {
  use id <- decode.field("id", decode.int)
  use name <- decode.field("name", decode.string)
  use price <- decode.field("price", decode.int)
  use stock <- decode.field("stock", decode.int)
  decode.success(cart.Product(id: id, name: name, price: price, stock: stock))
}

fn server_decode_cartitem() -> decode.Decoder(cart.CartItem) {
  use product_id <- decode.field("product_id", decode.int)
  use name <- decode.field("name", decode.string)
  use price <- decode.field("price", decode.int)
  use quantity <- decode.field("quantity", decode.int)
  decode.success(cart.CartItem(product_id: product_id, name: name, price: price, quantity: quantity))
}



/// Encode the Model to JSON for model_sync.
pub fn encode_model(state: #(cart.Model, cart.Local, Nil)) -> String {
  let model = state.0
  json.object([
    #("products", json.array(model.products, encode_product)),
    #("cart_items", json.array(model.cart_items, encode_cartitem)),
  ])
  |> json.to_string
}

/// Render the model with the same generated server contract used for SSR.
pub fn render_model(state: #(cart.Model, cart.Local, Nil)) -> String {
  let model = state.0
  let local = state.1
  cart.view(model, local)
  |> element.to_string
}

/// Decode a #(Model, Local, Server) from JSON string (for applying client patches).
pub fn decode_model(json_str: String) -> Result(#(cart.Model, cart.Local, Nil), String) {
  let state_decoder = {
    use products <- decode.field("products", decode.list(server_decode_product()))
    use cart_items <- decode.field("cart_items", decode.list(server_decode_cartitem()))

    decode.success(#(cart.Model(products: products, cart_items: cart_items), cart.Local, Nil))
  }
  case json.parse(json_str, state_decoder) {
    Ok(state) -> Ok(state)
    Error(_) -> Error("Failed to decode model+local+server")
  }
}

/// Decode the generated client event contract. Live event decoding never
/// renders the server view or reads the handler registry.
pub fn decode_event(_name: String, _handler_id: String, data: String, _target_path: String) -> Result(cart.Msg, String) {
  let envelope_decoder = {
    use msg_json <- decode.field("__beacon_msg", decode.string)
    decode.success(msg_json)
  }
  case json.parse(data, envelope_decoder) {
    Ok(msg_json) -> decode_msg(msg_json)
    Error(_) -> Error("Client event missing generated Beacon message envelope")
  }
}


fn decode_msg(json_str: String) -> Result(cart.Msg, String) {
  let tag_decoder = {
    use tag <- decode.field("tag", decode.string)
    decode.success(tag)
  }
  case json.parse(json_str, tag_decoder) {
    Ok(tag) -> {
      case tag {
    "AddToCart" -> {
      let msg_decoder = {
      use arg0 <- decode.field("arg0", decode.string)
      decode.success(cart.AddToCart(arg0))
      }
      case json.parse(json_str, msg_decoder) {
        Ok(msg) -> Ok(msg)
        Error(_) -> Error("Generated Beacon message payload did not match tag AddToCart")
      }
    }
    "RemoveFromCart" -> {
      let msg_decoder = {
      use arg0 <- decode.field("arg0", decode.string)
      decode.success(cart.RemoveFromCart(arg0))
      }
      case json.parse(json_str, msg_decoder) {
        Ok(msg) -> Ok(msg)
        Error(_) -> Error("Generated Beacon message payload did not match tag RemoveFromCart")
      }
    }
    "IncrementQty" -> {
      let msg_decoder = {
      use arg0 <- decode.field("arg0", decode.string)
      decode.success(cart.IncrementQty(arg0))
      }
      case json.parse(json_str, msg_decoder) {
        Ok(msg) -> Ok(msg)
        Error(_) -> Error("Generated Beacon message payload did not match tag IncrementQty")
      }
    }
    "DecrementQty" -> {
      let msg_decoder = {
      use arg0 <- decode.field("arg0", decode.string)
      decode.success(cart.DecrementQty(arg0))
      }
      case json.parse(json_str, msg_decoder) {
        Ok(msg) -> Ok(msg)
        Error(_) -> Error("Generated Beacon message payload did not match tag DecrementQty")
      }
    }
    "StockUpdated" -> {
      let msg_decoder = {
      decode.success(cart.StockUpdated)
      }
      case json.parse(json_str, msg_decoder) {
        Ok(msg) -> Ok(msg)
        Error(_) -> Error("Generated Beacon message payload did not match tag StockUpdated")
      }
    }
    "SetProducts" -> {
      let msg_decoder = {
      use arg0 <- decode.field("arg0", decode.list(server_decode_product()))
      decode.success(cart.SetProducts(arg0))
      }
      case json.parse(json_str, msg_decoder) {
        Ok(msg) -> Ok(msg)
        Error(_) -> Error("Generated Beacon message payload did not match tag SetProducts")
      }
    }
        _ -> Error("Unknown generated Beacon message tag " <> tag)
      }
    }
    Error(_) -> Error("Generated Beacon message payload missing tag")
  }
}

pub fn encode_substate_products(state: #(cart.Model, cart.Local, Nil)) -> String {
  let model = state.0
  json.array(model.products, encode_product)
  |> json.to_string
}

pub fn encode_substate_cart_items(state: #(cart.Model, cart.Local, Nil)) -> String {
  let model = state.0
  json.array(model.cart_items, encode_cartitem)
  |> json.to_string
}

pub fn substate_names() -> List(String) {
  ["products", "cart_items"]
}

pub fn encode_flat_fields(_state: #(cart.Model, cart.Local, Nil)) -> String {
  json.object([])
  |> json.to_string
}
