/// AUTO-GENERATED by beacon/build — do not edit manually.
/// Re-run `gleam run -m beacon/build` to regenerate.
import beacon/element
import canvas
import gleam/dynamic/decode
import gleam/json

fn encode_stroke(s: canvas.Stroke) -> json.Json {
  json.object([
    #("x1", json.int(s.x1)),
    #("y1", json.int(s.y1)),
    #("x2", json.int(s.x2)),
    #("y2", json.int(s.y2)),
    #("color", json.string(s.color)),
  ])
}

fn server_decode_stroke() -> decode.Decoder(canvas.Stroke) {
  use x1 <- decode.field("x1", decode.int)
  use y1 <- decode.field("y1", decode.int)
  use x2 <- decode.field("x2", decode.int)
  use y2 <- decode.field("y2", decode.int)
  use color <- decode.field("color", decode.string)
  decode.success(canvas.Stroke(x1: x1, y1: y1, x2: x2, y2: y2, color: color))
}

/// Encode the Model to JSON for model_sync.
pub fn encode_model(state: #(canvas.Model, canvas.Local, Nil)) -> String {
  let model = state.0
  let local = state.1
  json.object([
    #("strokes", json.array(model.strokes, encode_stroke)),
    #("color", json.string(model.color)),
    #("drawing", json.bool(local.drawing)),
    #("cursor_x", json.int(local.cursor_x)),
    #("cursor_y", json.int(local.cursor_y)),
    #("pending_strokes", json.array(local.pending_strokes, encode_stroke)),
  ])
  |> json.to_string
}

/// Render the model with the same generated server contract used for SSR.
pub fn render_model(state: #(canvas.Model, canvas.Local, Nil)) -> String {
  let model = state.0
  let local = state.1
  canvas.view(model, local)
  |> element.to_string
}

/// Decode a #(Model, Local, Server) from JSON string (for applying client patches).
pub fn decode_model(
  json_str: String,
) -> Result(#(canvas.Model, canvas.Local, Nil), String) {
  let state_decoder = {
    use strokes <- decode.field("strokes", decode.list(server_decode_stroke()))
    use color <- decode.field("color", decode.string)
    use drawing <- decode.field("drawing", decode.bool)
    use cursor_x <- decode.field("cursor_x", decode.int)
    use cursor_y <- decode.field("cursor_y", decode.int)
    use pending_strokes <- decode.field(
      "pending_strokes",
      decode.list(server_decode_stroke()),
    )
    decode.success(#(
      canvas.Model(strokes: strokes, color: color),
      canvas.Local(
        drawing: drawing,
        cursor_x: cursor_x,
        cursor_y: cursor_y,
        pending_strokes: pending_strokes,
      ),
      Nil,
    ))
  }
  case json.parse(json_str, state_decoder) {
    Ok(state) -> Ok(state)
    Error(_) -> Error("Failed to decode model+local+server")
  }
}

/// Decode the generated client event contract. Live event decoding never
/// renders the server view or reads the handler registry.
pub fn decode_event(
  _name: String,
  _handler_id: String,
  data: String,
  _target_path: String,
) -> Result(canvas.Msg, String) {
  let envelope_decoder = {
    use msg_json <- decode.field("__beacon_msg", decode.string)
    decode.success(msg_json)
  }
  case json.parse(data, envelope_decoder) {
    Ok(msg_json) -> decode_msg(msg_json)
    Error(_) -> Error("Client event missing generated Beacon message envelope")
  }
}

fn decode_msg(json_str: String) -> Result(canvas.Msg, String) {
  let tag_decoder = {
    use tag <- decode.field("tag", decode.string)
    decode.success(tag)
  }
  case json.parse(json_str, tag_decoder) {
    Ok(tag) -> {
      case tag {
        "StartDrawing" -> {
          let msg_decoder = {
            use arg0 <- decode.field("arg0", decode.string)
            decode.success(canvas.StartDrawing(arg0))
          }
          case json.parse(json_str, msg_decoder) {
            Ok(msg) -> Ok(msg)
            Error(_) ->
              Error(
                "Generated Beacon message payload did not match tag StartDrawing",
              )
          }
        }
        "MoveCursor" -> {
          let msg_decoder = {
            use arg0 <- decode.field("arg0", decode.string)
            decode.success(canvas.MoveCursor(arg0))
          }
          case json.parse(json_str, msg_decoder) {
            Ok(msg) -> Ok(msg)
            Error(_) ->
              Error(
                "Generated Beacon message payload did not match tag MoveCursor",
              )
          }
        }
        "StopDrawing" -> {
          let msg_decoder = {
            use arg0 <- decode.field("arg0", decode.string)
            decode.success(canvas.StopDrawing(arg0))
          }
          case json.parse(json_str, msg_decoder) {
            Ok(msg) -> Ok(msg)
            Error(_) ->
              Error(
                "Generated Beacon message payload did not match tag StopDrawing",
              )
          }
        }
        "SetColor" -> {
          let msg_decoder = {
            use arg0 <- decode.field("arg0", decode.string)
            decode.success(canvas.SetColor(arg0))
          }
          case json.parse(json_str, msg_decoder) {
            Ok(msg) -> Ok(msg)
            Error(_) ->
              Error(
                "Generated Beacon message payload did not match tag SetColor",
              )
          }
        }
        "ClearCanvas" -> {
          let msg_decoder = {
            decode.success(canvas.ClearCanvas)
          }
          case json.parse(json_str, msg_decoder) {
            Ok(msg) -> Ok(msg)
            Error(_) ->
              Error(
                "Generated Beacon message payload did not match tag ClearCanvas",
              )
          }
        }
        "StrokesUpdated" -> {
          let msg_decoder = {
            decode.success(canvas.StrokesUpdated)
          }
          case json.parse(json_str, msg_decoder) {
            Ok(msg) -> Ok(msg)
            Error(_) ->
              Error(
                "Generated Beacon message payload did not match tag StrokesUpdated",
              )
          }
        }
        "SetStrokes" -> {
          let msg_decoder = {
            use arg0 <- decode.field(
              "arg0",
              decode.list(server_decode_stroke()),
            )
            decode.success(canvas.SetStrokes(arg0))
          }
          case json.parse(json_str, msg_decoder) {
            Ok(msg) -> Ok(msg)
            Error(_) ->
              Error(
                "Generated Beacon message payload did not match tag SetStrokes",
              )
          }
        }
        _ -> Error("Unknown generated Beacon message tag " <> tag)
      }
    }
    Error(_) -> Error("Generated Beacon message payload missing tag")
  }
}

pub fn encode_substate_strokes(
  state: #(canvas.Model, canvas.Local, Nil),
) -> String {
  let model = state.0
  json.array(model.strokes, encode_stroke)
  |> json.to_string
}

pub fn substate_names() -> List(String) {
  ["strokes"]
}

pub fn encode_flat_fields(state: #(canvas.Model, canvas.Local, Nil)) -> String {
  let model = state.0
  json.object([
    #("color", json.string(model.color)),
  ])
  |> json.to_string
}
