/// AUTO-GENERATED by beacon/build — do not edit manually.
/// Re-run `gleam run -m beacon/build` to regenerate.

import app
import domains/task as task
import beacon/element
import gleam/json
import gleam/dynamic/decode

fn encode_task_todoitem(s: task.TodoItem) -> json.Json {
  json.object([
    #("id", json.int(s.id)),
    #("text", json.string(s.text)),
    #("completed", json.bool(s.completed)),
  ])
}

fn encode_task_filter(value: task.Filter) -> String {
  case value {
    task.All -> "all"
    task.Active -> "active"
    task.Completed -> "completed"
  }
}

fn server_decode_task_todoitem() -> decode.Decoder(task.TodoItem) {
  use id <- decode.field("id", decode.int)
  use text <- decode.field("text", decode.string)
  use completed <- decode.field("completed", decode.bool)
  decode.success(task.TodoItem(id: id, text: text, completed: completed))
}

fn server_decode_task_filter_value(s: String) -> task.Filter {
  case s {
    "all" -> task.All
    "active" -> task.Active
    "completed" -> task.Completed
    _ -> task.All
  }
}

/// Encode the Model to JSON for model_sync.
pub fn encode_model(state: #(app.Model, app.Local)) -> String {
  let model = state.0
  let local = state.1
  json.object([
    #("todos", json.array(model.todos, encode_task_todoitem)),
    #("input", json.string(model.input)),
    #("next_id", json.int(model.next_id)),
    #("filter", json.string(encode_task_filter(local.filter))),
  ])
  |> json.to_string
}

/// Render the model with the same generated server contract used for SSR.
pub fn render_model(state: #(app.Model, app.Local)) -> String {
  let model = state.0
  let local = state.1
  app.view(model, local)
  |> element.to_string
}

/// Decode a #(Model, Local) from JSON string (for applying client patches).
pub fn decode_model(json_str: String) -> Result(#(app.Model, app.Local), String) {
  let state_decoder = {
    use todos <- decode.field("todos", decode.list(server_decode_task_todoitem()))
    use input <- decode.field("input", decode.string)
    use next_id <- decode.field("next_id", decode.int)
    use filter <- decode.field("filter", decode.string)
    decode.success(#(app.Model(todos: todos, input: input, next_id: next_id), app.Local(filter: server_decode_task_filter_value(filter))))
  }
  case json.parse(json_str, state_decoder) {
    Ok(state) -> Ok(state)
    Error(_) -> Error("Failed to decode model+local")
  }
}

/// Decode the generated client event contract. Live event decoding never
/// renders the server view or reads the handler registry.
pub fn decode_event(_name: String, _handler_id: String, data: String, _target_path: String) -> Result(app.Msg, String) {
  let envelope_decoder = {
    use msg_json <- decode.field("__beacon_msg", decode.string)
    decode.success(msg_json)
  }
  case json.parse(data, envelope_decoder) {
    Ok(msg_json) -> decode_msg(msg_json)
    Error(_) -> Error("Client event missing generated Beacon message envelope")
  }
}


fn decode_msg(json_str: String) -> Result(app.Msg, String) {
  let tag_decoder = {
    use tag <- decode.field("tag", decode.string)
    decode.success(tag)
  }
  case json.parse(json_str, tag_decoder) {
    Ok(tag) -> {
      case tag {
    "SetInput" -> {
      let msg_decoder = {
      use arg0 <- decode.field("arg0", decode.string)
      decode.success(app.SetInput(arg0))
      }
      case json.parse(json_str, msg_decoder) {
        Ok(msg) -> Ok(msg)
        Error(_) -> Error("Generated Beacon message payload did not match tag SetInput")
      }
    }
    "AddTodo" -> {
      let msg_decoder = {
      decode.success(app.AddTodo)
      }
      case json.parse(json_str, msg_decoder) {
        Ok(msg) -> Ok(msg)
        Error(_) -> Error("Generated Beacon message payload did not match tag AddTodo")
      }
    }
    "ToggleTodo" -> {
      let msg_decoder = {
      use arg0 <- decode.field("arg0", decode.int)
      decode.success(app.ToggleTodo(arg0))
      }
      case json.parse(json_str, msg_decoder) {
        Ok(msg) -> Ok(msg)
        Error(_) -> Error("Generated Beacon message payload did not match tag ToggleTodo")
      }
    }
    "DeleteTodo" -> {
      let msg_decoder = {
      use arg0 <- decode.field("arg0", decode.int)
      decode.success(app.DeleteTodo(arg0))
      }
      case json.parse(json_str, msg_decoder) {
        Ok(msg) -> Ok(msg)
        Error(_) -> Error("Generated Beacon message payload did not match tag DeleteTodo")
      }
    }
    "SetFilter" -> {
      let msg_decoder = {
      use arg0 <- decode.field("arg0", decode.string)
      decode.success(app.SetFilter(arg0))
      }
      case json.parse(json_str, msg_decoder) {
        Ok(msg) -> Ok(msg)
        Error(_) -> Error("Generated Beacon message payload did not match tag SetFilter")
      }
    }
    "ClearCompleted" -> {
      let msg_decoder = {
      decode.success(app.ClearCompleted)
      }
      case json.parse(json_str, msg_decoder) {
        Ok(msg) -> Ok(msg)
        Error(_) -> Error("Generated Beacon message payload did not match tag ClearCompleted")
      }
    }
        _ -> Error("Unknown generated Beacon message tag " <> tag)
      }
    }
    Error(_) -> Error("Generated Beacon message payload missing tag")
  }
}

pub fn encode_substate_todos(state: #(app.Model, app.Local)) -> String {
  let model = state.0
  json.array(model.todos, encode_task_todoitem)
  |> json.to_string
}

pub fn substate_names() -> List(String) {
  ["todos"]
}

pub fn encode_flat_fields(state: #(app.Model, app.Local)) -> String {
  let model = state.0
  json.object([
    #("input", json.string(model.input)),
    #("next_id", json.int(model.next_id)),
  ])
  |> json.to_string
}
