/// AUTO-GENERATED by beacon/build — do not edit manually.
/// Re-run `gleam run -m beacon/build` to regenerate.
import beacon/element
import gleam/dynamic/decode
import gleam/json
import snake

fn encode_point(s: snake.Point) -> json.Json {
  json.object([
    #("x", json.int(s.x)),
    #("y", json.int(s.y)),
  ])
}

fn encode_gamestate(value: snake.GameState) -> String {
  case value {
    snake.Playing -> "playing"
    snake.GameOver -> "gameover"
  }
}

fn encode_direction(value: snake.Direction) -> String {
  case value {
    snake.Up -> "up"
    snake.Down -> "down"
    snake.Left -> "left"
    snake.Right -> "right"
  }
}

fn server_decode_point() -> decode.Decoder(snake.Point) {
  use x <- decode.field("x", decode.int)
  use y <- decode.field("y", decode.int)
  decode.success(snake.Point(x: x, y: y))
}

fn server_decode_gamestate_value(s: String) -> snake.GameState {
  case s {
    "playing" -> snake.Playing
    "gameover" -> snake.GameOver
    _ -> snake.Playing
  }
}

fn server_decode_direction_value(s: String) -> snake.Direction {
  case s {
    "up" -> snake.Up
    "down" -> snake.Down
    "left" -> snake.Left
    "right" -> snake.Right
    _ -> snake.Up
  }
}

/// Encode the Model to JSON for model_sync.
pub fn encode_model(state: #(snake.Model, Nil, Nil)) -> String {
  let model = state.0
  json.object([
    #("snake", json.array(model.snake, encode_point)),
    #("direction", json.string(encode_direction(model.direction))),
    #("food", encode_point(model.food)),
    #("score", json.int(model.score)),
    #("game_state", json.string(encode_gamestate(model.game_state))),
    #("grid_width", json.int(model.grid_width)),
    #("grid_height", json.int(model.grid_height)),
    #("player_name", json.string(model.player_name)),
    #("name_input", json.string(model.name_input)),
    #("has_name", json.bool(model.has_name)),
    #("high_score_pending", json.bool(model.high_score_pending)),
  ])
  |> json.to_string
}

/// Render the model with the same generated server contract used for SSR.
pub fn render_model(state: #(snake.Model, Nil, Nil)) -> String {
  let model = state.0
  let local = Nil
  snake.view(model, local)
  |> element.to_string
}

/// Decode a #(Model, Local, Server) from JSON string (for applying client patches).
pub fn decode_model(
  json_str: String,
) -> Result(#(snake.Model, Nil, Nil), String) {
  let state_decoder = {
    use snake <- decode.field("snake", decode.list(server_decode_point()))
    use direction <- decode.field("direction", decode.string)
    use food <- decode.field("food", server_decode_point())
    use score <- decode.field("score", decode.int)
    use game_state <- decode.field("game_state", decode.string)
    use grid_width <- decode.field("grid_width", decode.int)
    use grid_height <- decode.field("grid_height", decode.int)
    use player_name <- decode.field("player_name", decode.string)
    use name_input <- decode.field("name_input", decode.string)
    use has_name <- decode.field("has_name", decode.bool)
    use high_score_pending <- decode.field("high_score_pending", decode.bool)

    decode.success(#(
      snake.Model(
        snake: snake,
        direction: server_decode_direction_value(direction),
        food: food,
        score: score,
        game_state: server_decode_gamestate_value(game_state),
        grid_width: grid_width,
        grid_height: grid_height,
        player_name: player_name,
        name_input: name_input,
        has_name: has_name,
        high_score_pending: high_score_pending,
      ),
      Nil,
      Nil,
    ))
  }
  case json.parse(json_str, state_decoder) {
    Ok(state) -> Ok(state)
    Error(_) -> Error("Failed to decode model+local+server")
  }
}

/// Decode the generated client event contract. Live event decoding never
/// renders the server view or reads the handler registry.
pub fn decode_event(
  _name: String,
  _handler_id: String,
  data: String,
  _target_path: String,
) -> Result(snake.Msg, String) {
  let envelope_decoder = {
    use msg_json <- decode.field("__beacon_msg", decode.string)
    decode.success(msg_json)
  }
  case json.parse(data, envelope_decoder) {
    Ok(msg_json) -> decode_msg(msg_json)
    Error(_) -> Error("Client event missing generated Beacon message envelope")
  }
}

fn decode_msg(json_str: String) -> Result(snake.Msg, String) {
  let tag_decoder = {
    use tag <- decode.field("tag", decode.string)
    decode.success(tag)
  }
  case json.parse(json_str, tag_decoder) {
    Ok(tag) -> {
      case tag {
        "Tick" -> {
          let msg_decoder = {
            decode.success(snake.Tick)
          }
          case json.parse(json_str, msg_decoder) {
            Ok(msg) -> Ok(msg)
            Error(_) ->
              Error("Generated Beacon message payload did not match tag Tick")
          }
        }
        "ChangeDirection" -> {
          let msg_decoder = {
            use arg0 <- decode.field("arg0", decode.string)
            decode.success(
              snake.ChangeDirection(server_decode_direction_value(arg0)),
            )
          }
          case json.parse(json_str, msg_decoder) {
            Ok(msg) -> Ok(msg)
            Error(_) ->
              Error(
                "Generated Beacon message payload did not match tag ChangeDirection",
              )
          }
        }
        "RestartGame" -> {
          let msg_decoder = {
            decode.success(snake.RestartGame)
          }
          case json.parse(json_str, msg_decoder) {
            Ok(msg) -> Ok(msg)
            Error(_) ->
              Error(
                "Generated Beacon message payload did not match tag RestartGame",
              )
          }
        }
        "UpdateNameInput" -> {
          let msg_decoder = {
            use arg0 <- decode.field("arg0", decode.string)
            decode.success(snake.UpdateNameInput(arg0))
          }
          case json.parse(json_str, msg_decoder) {
            Ok(msg) -> Ok(msg)
            Error(_) ->
              Error(
                "Generated Beacon message payload did not match tag UpdateNameInput",
              )
          }
        }
        "SetName" -> {
          let msg_decoder = {
            decode.success(snake.SetName)
          }
          case json.parse(json_str, msg_decoder) {
            Ok(msg) -> Ok(msg)
            Error(_) ->
              Error(
                "Generated Beacon message payload did not match tag SetName",
              )
          }
        }
        "HighScoreUpdated" -> {
          let msg_decoder = {
            decode.success(snake.HighScoreUpdated)
          }
          case json.parse(json_str, msg_decoder) {
            Ok(msg) -> Ok(msg)
            Error(_) ->
              Error(
                "Generated Beacon message payload did not match tag HighScoreUpdated",
              )
          }
        }
        _ -> Error("Unknown generated Beacon message tag " <> tag)
      }
    }
    Error(_) -> Error("Generated Beacon message payload missing tag")
  }
}

pub fn encode_substate_snake(state: #(snake.Model, Nil, Nil)) -> String {
  let model = state.0
  json.array(model.snake, encode_point)
  |> json.to_string
}

pub fn encode_substate_food(state: #(snake.Model, Nil, Nil)) -> String {
  let model = state.0
  encode_point(model.food)
  |> json.to_string
}

pub fn substate_names() -> List(String) {
  ["snake", "food"]
}

pub fn encode_flat_fields(state: #(snake.Model, Nil, Nil)) -> String {
  let model = state.0
  json.object([
    #("direction", json.string(encode_direction(model.direction))),
    #("score", json.int(model.score)),
    #("game_state", json.string(encode_gamestate(model.game_state))),
    #("grid_width", json.int(model.grid_width)),
    #("grid_height", json.int(model.grid_height)),
    #("player_name", json.string(model.player_name)),
    #("name_input", json.string(model.name_input)),
    #("has_name", json.bool(model.has_name)),
    #("high_score_pending", json.bool(model.high_score_pending)),
  ])
  |> json.to_string
}
