/// AUTO-GENERATED by beacon/build — do not edit manually.
/// Re-run `gleam run -m beacon/build` to regenerate.

import privacy_demo
import gleam/json

fn encode_item(s: privacy_demo.Item) -> json.Json {
  json.object([
    #("name", json.string(s.name)),
    #("price", json.int(s.price)),
    #("qty", json.int(s.qty)),
  ])
}







/// Encode the Model to JSON for model_sync.
pub fn encode_model(state: #(privacy_demo.Model, privacy_demo.Server)) -> String {
  let model = state.0
  json.object([
    #("items", json.array(model.items, encode_item)),
    #("tax_rate", json.float(model.tax_rate)),
    #("item_count", json.int(privacy_demo.item_count(model))),
    #("total", json.int(privacy_demo.total(model))),
    #("subtotal", json.int(privacy_demo.subtotal(model))),
  ])
  |> json.to_string
}

/// Decode is not supported for app_with_server — Server state cannot be reconstructed from client JSON.
pub fn decode_model(_json_str: String) -> Result(#(privacy_demo.Model, privacy_demo.Server), String) {
  Error("decode_model not supported for app_with_server")
}

pub fn encode_substate_items(state: #(privacy_demo.Model, privacy_demo.Server)) -> String {
  let model = state.0
  json.array(model.items, encode_item)
  |> json.to_string
}

pub fn substate_names() -> List(String) {
  ["items"]
}

pub fn encode_flat_fields(state: #(privacy_demo.Model, privacy_demo.Server)) -> String {
  let model = state.0
  json.object([
    #("tax_rate", json.float(model.tax_rate)),
  ])
  |> json.to_string
}
