/// AUTO-GENERATED by beacon/build — do not edit manually.
/// Re-run `gleam run -m beacon/build` to regenerate.
import beacon/element
import gleam/dynamic/decode
import gleam/json
import kanban

fn encode_card(s: kanban.Card) -> json.Json {
  json.object([
    #("id", json.int(s.id)),
    #("title", json.string(s.title)),
    #("column", json.string(encode_column(s.column))),
  ])
}

fn encode_column(value: kanban.Column) -> String {
  case value {
    kanban.Todo -> "todo"
    kanban.Doing -> "doing"
    kanban.Done -> "done"
  }
}

fn server_decode_card() -> decode.Decoder(kanban.Card) {
  use id <- decode.field("id", decode.int)
  use title <- decode.field("title", decode.string)
  use column <- decode.field("column", decode.string)
  decode.success(kanban.Card(
    id: id,
    title: title,
    column: server_decode_column_value(column),
  ))
}

fn server_decode_column_value(s: String) -> kanban.Column {
  case s {
    "todo" -> kanban.Todo
    "doing" -> kanban.Doing
    "done" -> kanban.Done
    _ -> kanban.Todo
  }
}

/// Encode the Model to JSON for model_sync.
pub fn encode_model(state: #(kanban.Model, kanban.Local, Nil)) -> String {
  let model = state.0
  json.object([
    #("cards", json.array(model.cards, encode_card)),
    #("next_id", json.int(model.next_id)),
    #("new_card_input", json.string(model.new_card_input)),
    #("dragging_id", json.int(model.dragging_id)),
  ])
  |> json.to_string
}

/// Render the model with the same generated server contract used for SSR.
pub fn render_model(state: #(kanban.Model, kanban.Local, Nil)) -> String {
  let model = state.0
  let local = state.1
  kanban.view(model, local)
  |> element.to_string
}

/// Decode a #(Model, Local, Server) from JSON string (for applying client patches).
pub fn decode_model(
  json_str: String,
) -> Result(#(kanban.Model, kanban.Local, Nil), String) {
  let state_decoder = {
    use cards <- decode.field("cards", decode.list(server_decode_card()))
    use next_id <- decode.field("next_id", decode.int)
    use new_card_input <- decode.field("new_card_input", decode.string)
    use dragging_id <- decode.field("dragging_id", decode.int)

    decode.success(#(
      kanban.Model(
        cards: cards,
        next_id: next_id,
        new_card_input: new_card_input,
        dragging_id: dragging_id,
      ),
      kanban.Local,
      Nil,
    ))
  }
  case json.parse(json_str, state_decoder) {
    Ok(state) -> Ok(state)
    Error(_) -> Error("Failed to decode model+local+server")
  }
}

/// Decode the generated client event contract. Live event decoding never
/// renders the server view or reads the handler registry.
pub fn decode_event(
  _name: String,
  _handler_id: String,
  data: String,
  _target_path: String,
) -> Result(kanban.Msg, String) {
  let envelope_decoder = {
    use msg_json <- decode.field("__beacon_msg", decode.string)
    decode.success(msg_json)
  }
  case json.parse(data, envelope_decoder) {
    Ok(msg_json) -> decode_msg(msg_json)
    Error(_) -> Error("Client event missing generated Beacon message envelope")
  }
}

fn decode_msg(json_str: String) -> Result(kanban.Msg, String) {
  let tag_decoder = {
    use tag <- decode.field("tag", decode.string)
    decode.success(tag)
  }
  case json.parse(json_str, tag_decoder) {
    Ok(tag) -> {
      case tag {
        "UpdateInput" -> {
          let msg_decoder = {
            use arg0 <- decode.field("arg0", decode.string)
            decode.success(kanban.UpdateInput(arg0))
          }
          case json.parse(json_str, msg_decoder) {
            Ok(msg) -> Ok(msg)
            Error(_) ->
              Error(
                "Generated Beacon message payload did not match tag UpdateInput",
              )
          }
        }
        "AddCard" -> {
          let msg_decoder = {
            decode.success(kanban.AddCard)
          }
          case json.parse(json_str, msg_decoder) {
            Ok(msg) -> Ok(msg)
            Error(_) ->
              Error(
                "Generated Beacon message payload did not match tag AddCard",
              )
          }
        }
        "StartDrag" -> {
          let msg_decoder = {
            use arg0 <- decode.field("arg0", decode.string)
            decode.success(kanban.StartDrag(arg0))
          }
          case json.parse(json_str, msg_decoder) {
            Ok(msg) -> Ok(msg)
            Error(_) ->
              Error(
                "Generated Beacon message payload did not match tag StartDrag",
              )
          }
        }
        "DropOnColumn" -> {
          let msg_decoder = {
            use arg0 <- decode.field("arg0", decode.string)
            decode.success(kanban.DropOnColumn(arg0))
          }
          case json.parse(json_str, msg_decoder) {
            Ok(msg) -> Ok(msg)
            Error(_) ->
              Error(
                "Generated Beacon message payload did not match tag DropOnColumn",
              )
          }
        }
        "DragOverColumn" -> {
          let msg_decoder = {
            decode.success(kanban.DragOverColumn)
          }
          case json.parse(json_str, msg_decoder) {
            Ok(msg) -> Ok(msg)
            Error(_) ->
              Error(
                "Generated Beacon message payload did not match tag DragOverColumn",
              )
          }
        }
        "DeleteCard" -> {
          let msg_decoder = {
            use arg0 <- decode.field("arg0", decode.int)
            decode.success(kanban.DeleteCard(arg0))
          }
          case json.parse(json_str, msg_decoder) {
            Ok(msg) -> Ok(msg)
            Error(_) ->
              Error(
                "Generated Beacon message payload did not match tag DeleteCard",
              )
          }
        }
        "BoardUpdated" -> {
          let msg_decoder = {
            decode.success(kanban.BoardUpdated)
          }
          case json.parse(json_str, msg_decoder) {
            Ok(msg) -> Ok(msg)
            Error(_) ->
              Error(
                "Generated Beacon message payload did not match tag BoardUpdated",
              )
          }
        }
        "SetCards" -> {
          let msg_decoder = {
            use arg0 <- decode.field("arg0", decode.list(server_decode_card()))
            use arg1 <- decode.field("arg1", decode.int)
            decode.success(kanban.SetCards(arg0, arg1))
          }
          case json.parse(json_str, msg_decoder) {
            Ok(msg) -> Ok(msg)
            Error(_) ->
              Error(
                "Generated Beacon message payload did not match tag SetCards",
              )
          }
        }
        _ -> Error("Unknown generated Beacon message tag " <> tag)
      }
    }
    Error(_) -> Error("Generated Beacon message payload missing tag")
  }
}

pub fn encode_substate_cards(
  state: #(kanban.Model, kanban.Local, Nil),
) -> String {
  let model = state.0
  json.array(model.cards, encode_card)
  |> json.to_string
}

pub fn substate_names() -> List(String) {
  ["cards"]
}

pub fn encode_flat_fields(state: #(kanban.Model, kanban.Local, Nil)) -> String {
  let model = state.0
  json.object([
    #("next_id", json.int(model.next_id)),
    #("new_card_input", json.string(model.new_card_input)),
    #("dragging_id", json.int(model.dragging_id)),
  ])
  |> json.to_string
}
