/// AUTO-GENERATED by beacon/build — do not edit manually.
/// Re-run `gleam run -m beacon/build` to regenerate.

import dashboard
import beacon/element
import gleam/json
import gleam/dynamic/decode









/// Encode the Model to JSON for model_sync.
pub fn encode_model(state: #(dashboard.Model, Nil, Nil)) -> String {
  let model = state.0
  json.object([
    #("process_count", json.int(model.process_count)),
    #("memory_mb", json.float(model.memory_mb)),
    #("uptime_seconds", json.int(model.uptime_seconds)),
    #("process_history", json.array(model.process_history, json.int)),
    #("memory_history", json.array(model.memory_history, json.float)),
    #("tick_count", json.int(model.tick_count)),
  ])
  |> json.to_string
}

/// Render the model with the same generated server contract used for SSR.
pub fn render_model(state: #(dashboard.Model, Nil, Nil)) -> String {
  let model = state.0
  let local = Nil
  dashboard.view(model, local)
  |> element.to_string
}

/// Decode a #(Model, Local, Server) from JSON string (for applying client patches).
pub fn decode_model(json_str: String) -> Result(#(dashboard.Model, Nil, Nil), String) {
  let state_decoder = {
    use process_count <- decode.field("process_count", decode.int)
    use memory_mb <- decode.field("memory_mb", decode.float)
    use uptime_seconds <- decode.field("uptime_seconds", decode.int)
    use process_history <- decode.field("process_history", decode.list(decode.int))
    use memory_history <- decode.field("memory_history", decode.list(decode.float))
    use tick_count <- decode.field("tick_count", decode.int)

    decode.success(#(dashboard.Model(process_count: process_count, memory_mb: memory_mb, uptime_seconds: uptime_seconds, process_history: process_history, memory_history: memory_history, tick_count: tick_count), Nil, Nil))
  }
  case json.parse(json_str, state_decoder) {
    Ok(state) -> Ok(state)
    Error(_) -> Error("Failed to decode model+local+server")
  }
}

/// Decode the generated client event contract. Live event decoding never
/// renders the server view or reads the handler registry.
pub fn decode_event(_name: String, _handler_id: String, data: String, _target_path: String) -> Result(dashboard.Msg, String) {
  let envelope_decoder = {
    use msg_json <- decode.field("__beacon_msg", decode.string)
    decode.success(msg_json)
  }
  case json.parse(data, envelope_decoder) {
    Ok(msg_json) -> decode_msg(msg_json)
    Error(_) -> Error("Client event missing generated Beacon message envelope")
  }
}


fn decode_msg(json_str: String) -> Result(dashboard.Msg, String) {
  let tag_decoder = {
    use tag <- decode.field("tag", decode.string)
    decode.success(tag)
  }
  case json.parse(json_str, tag_decoder) {
    Ok(tag) -> {
      case tag {
    "RefreshStats" -> {
      let msg_decoder = {
      decode.success(dashboard.RefreshStats)
      }
      case json.parse(json_str, msg_decoder) {
        Ok(msg) -> Ok(msg)
        Error(_) -> Error("Generated Beacon message payload did not match tag RefreshStats")
      }
    }
        _ -> Error("Unknown generated Beacon message tag " <> tag)
      }
    }
    Error(_) -> Error("Generated Beacon message payload missing tag")
  }
}
