/// AUTO-GENERATED by beacon/build — do not edit manually.
/// Re-run `gleam run -m beacon/build` to regenerate.

import app
import domains/auth as auth
import domains/items as items
import beacon/element
import gleam/json
import gleam/dynamic/decode

fn encode_auth_user(s: auth.User) -> json.Json {
  json.object([
    #("name", json.string(s.name)),
    #("email", json.string(s.email)),
    #("role", json.string(encode_auth_role(s.role))),
  ])
}

fn encode_items_item(s: items.Item) -> json.Json {
  json.object([
    #("id", json.int(s.id)),
    #("name", json.string(s.name)),
    #("done", json.bool(s.done)),
  ])
}

fn encode_auth_role(value: auth.Role) -> String {
  case value {
    auth.Admin -> "admin"
    auth.Member -> "member"
    auth.Guest -> "guest"
  }
}

fn server_decode_auth_user() -> decode.Decoder(auth.User) {
  use name <- decode.field("name", decode.string)
  use email <- decode.field("email", decode.string)
  use role <- decode.field("role", decode.string)
  decode.success(auth.User(name: name, email: email, role: server_decode_auth_role_value(role)))
}

fn server_decode_items_item() -> decode.Decoder(items.Item) {
  use id <- decode.field("id", decode.int)
  use name <- decode.field("name", decode.string)
  use done <- decode.field("done", decode.bool)
  decode.success(items.Item(id: id, name: name, done: done))
}

fn server_decode_auth_role_value(s: String) -> auth.Role {
  case s {
    "admin" -> auth.Admin
    "member" -> auth.Member
    "guest" -> auth.Guest
    _ -> auth.Admin
  }
}

/// Encode the Model to JSON for model_sync.
pub fn encode_model(state: #(app.Model, Nil, Nil)) -> String {
  let model = state.0
  json.object([
    #("user", encode_auth_user(model.user)),
    #("items", json.array(model.items, encode_items_item)),
    #("next_id", json.int(model.next_id)),
    #("input", json.string(model.input)),
  ])
  |> json.to_string
}

/// Render the model with the same generated server contract used for SSR.
pub fn render_model(state: #(app.Model, Nil, Nil)) -> String {
  let model = state.0
  let local = Nil
  app.view(model, local)
  |> element.to_string
}

/// Decode a #(Model, Local, Server) from JSON string (for applying client patches).
pub fn decode_model(json_str: String) -> Result(#(app.Model, Nil, Nil), String) {
  let state_decoder = {
    use user <- decode.field("user", server_decode_auth_user())
    use items <- decode.field("items", decode.list(server_decode_items_item()))
    use next_id <- decode.field("next_id", decode.int)
    use input <- decode.field("input", decode.string)

    decode.success(#(app.Model(user: user, items: items, next_id: next_id, input: input), Nil, Nil))
  }
  case json.parse(json_str, state_decoder) {
    Ok(state) -> Ok(state)
    Error(_) -> Error("Failed to decode model+local+server")
  }
}

/// Decode the generated client event contract. Live event decoding never
/// renders the server view or reads the handler registry.
pub fn decode_event(_name: String, _handler_id: String, data: String, _target_path: String) -> Result(app.Msg, String) {
  let envelope_decoder = {
    use msg_json <- decode.field("__beacon_msg", decode.string)
    decode.success(msg_json)
  }
  case json.parse(data, envelope_decoder) {
    Ok(msg_json) -> decode_msg(msg_json)
    Error(_) -> Error("Client event missing generated Beacon message envelope")
  }
}


fn decode_msg(json_str: String) -> Result(app.Msg, String) {
  let tag_decoder = {
    use tag <- decode.field("tag", decode.string)
    decode.success(tag)
  }
  case json.parse(json_str, tag_decoder) {
    Ok(tag) -> {
      case tag {
    "SetInput" -> {
      let msg_decoder = {
      use arg0 <- decode.field("arg0", decode.string)
      decode.success(app.SetInput(arg0))
      }
      case json.parse(json_str, msg_decoder) {
        Ok(msg) -> Ok(msg)
        Error(_) -> Error("Generated Beacon message payload did not match tag SetInput")
      }
    }
    "AddItem" -> {
      let msg_decoder = {
      decode.success(app.AddItem)
      }
      case json.parse(json_str, msg_decoder) {
        Ok(msg) -> Ok(msg)
        Error(_) -> Error("Generated Beacon message payload did not match tag AddItem")
      }
    }
    "ToggleItem" -> {
      let msg_decoder = {
      use arg0 <- decode.field("arg0", decode.int)
      decode.success(app.ToggleItem(arg0))
      }
      case json.parse(json_str, msg_decoder) {
        Ok(msg) -> Ok(msg)
        Error(_) -> Error("Generated Beacon message payload did not match tag ToggleItem")
      }
    }
    "SetRole" -> {
      let msg_decoder = {
      use arg0 <- decode.field("arg0", decode.string)
      decode.success(app.SetRole(arg0))
      }
      case json.parse(json_str, msg_decoder) {
        Ok(msg) -> Ok(msg)
        Error(_) -> Error("Generated Beacon message payload did not match tag SetRole")
      }
    }
        _ -> Error("Unknown generated Beacon message tag " <> tag)
      }
    }
    Error(_) -> Error("Generated Beacon message payload missing tag")
  }
}

pub fn encode_substate_user(state: #(app.Model, Nil, Nil)) -> String {
  let model = state.0
  encode_auth_user(model.user)
  |> json.to_string
}

pub fn encode_substate_items(state: #(app.Model, Nil, Nil)) -> String {
  let model = state.0
  json.array(model.items, encode_items_item)
  |> json.to_string
}

pub fn substate_names() -> List(String) {
  ["user", "items"]
}

pub fn encode_flat_fields(state: #(app.Model, Nil, Nil)) -> String {
  let model = state.0
  json.object([
    #("next_id", json.int(model.next_id)),
    #("input", json.string(model.input)),
  ])
  |> json.to_string
}
