/// AUTO-GENERATED by beacon/build — do not edit manually.
/// Re-run `gleam run -m beacon/build` to regenerate.
import app
import beacon/element
import domains/board
import gleam/dynamic/decode
import gleam/json

fn encode_board_card(s: board.Card) -> json.Json {
  json.object([
    #("id", json.int(s.id)),
    #("title", json.string(s.title)),
    #("column", json.string(encode_board_column(s.column))),
  ])
}

fn encode_board_column(value: board.Column) -> String {
  case value {
    board.Todo -> "todo"
    board.Doing -> "doing"
    board.Done -> "done"
  }
}

fn server_decode_board_card() -> decode.Decoder(board.Card) {
  use id <- decode.field("id", decode.int)
  use title <- decode.field("title", decode.string)
  use column <- decode.field("column", decode.string)
  decode.success(board.Card(
    id: id,
    title: title,
    column: server_decode_board_column_value(column),
  ))
}

fn server_decode_board_column_value(s: String) -> board.Column {
  case s {
    "todo" -> board.Todo
    "doing" -> board.Doing
    "done" -> board.Done
    _ -> board.Todo
  }
}

/// Encode the Model to JSON for model_sync.
pub fn encode_model(state: #(app.Model, Nil, Nil)) -> String {
  let model = state.0
  json.object([
    #("cards", json.array(model.cards, encode_board_card)),
    #("next_id", json.int(model.next_id)),
    #("input", json.string(model.input)),
    #("dragging_id", json.int(model.dragging_id)),
  ])
  |> json.to_string
}

/// Render the model with the same generated server contract used for SSR.
pub fn render_model(state: #(app.Model, Nil, Nil)) -> String {
  let model = state.0
  let local = Nil
  app.view(model, local)
  |> element.to_string
}

/// Decode a #(Model, Local, Server) from JSON string (for applying client patches).
pub fn decode_model(json_str: String) -> Result(#(app.Model, Nil, Nil), String) {
  let state_decoder = {
    use cards <- decode.field("cards", decode.list(server_decode_board_card()))
    use next_id <- decode.field("next_id", decode.int)
    use input <- decode.field("input", decode.string)
    use dragging_id <- decode.field("dragging_id", decode.int)

    decode.success(#(
      app.Model(
        cards: cards,
        next_id: next_id,
        input: input,
        dragging_id: dragging_id,
      ),
      Nil,
      Nil,
    ))
  }
  case json.parse(json_str, state_decoder) {
    Ok(state) -> Ok(state)
    Error(_) -> Error("Failed to decode model+local+server")
  }
}

/// Decode the generated client event contract. Live event decoding never
/// renders the server view or reads the handler registry.
pub fn decode_event(
  _name: String,
  _handler_id: String,
  data: String,
  _target_path: String,
) -> Result(app.Msg, String) {
  let envelope_decoder = {
    use msg_json <- decode.field("__beacon_msg", decode.string)
    decode.success(msg_json)
  }
  case json.parse(data, envelope_decoder) {
    Ok(msg_json) -> decode_msg(msg_json)
    Error(_) -> Error("Client event missing generated Beacon message envelope")
  }
}

fn decode_msg(json_str: String) -> Result(app.Msg, String) {
  let tag_decoder = {
    use tag <- decode.field("tag", decode.string)
    decode.success(tag)
  }
  case json.parse(json_str, tag_decoder) {
    Ok(tag) -> {
      case tag {
        "SetInput" -> {
          let msg_decoder = {
            use arg0 <- decode.field("arg0", decode.string)
            decode.success(app.SetInput(arg0))
          }
          case json.parse(json_str, msg_decoder) {
            Ok(msg) -> Ok(msg)
            Error(_) ->
              Error(
                "Generated Beacon message payload did not match tag SetInput",
              )
          }
        }
        "AddCard" -> {
          let msg_decoder = {
            decode.success(app.AddCard)
          }
          case json.parse(json_str, msg_decoder) {
            Ok(msg) -> Ok(msg)
            Error(_) ->
              Error(
                "Generated Beacon message payload did not match tag AddCard",
              )
          }
        }
        "StartDrag" -> {
          let msg_decoder = {
            use arg0 <- decode.field("arg0", decode.string)
            decode.success(app.StartDrag(arg0))
          }
          case json.parse(json_str, msg_decoder) {
            Ok(msg) -> Ok(msg)
            Error(_) ->
              Error(
                "Generated Beacon message payload did not match tag StartDrag",
              )
          }
        }
        "DropOnColumn" -> {
          let msg_decoder = {
            use arg0 <- decode.field("arg0", decode.string)
            decode.success(app.DropOnColumn(arg0))
          }
          case json.parse(json_str, msg_decoder) {
            Ok(msg) -> Ok(msg)
            Error(_) ->
              Error(
                "Generated Beacon message payload did not match tag DropOnColumn",
              )
          }
        }
        "DragOverColumn" -> {
          let msg_decoder = {
            decode.success(app.DragOverColumn)
          }
          case json.parse(json_str, msg_decoder) {
            Ok(msg) -> Ok(msg)
            Error(_) ->
              Error(
                "Generated Beacon message payload did not match tag DragOverColumn",
              )
          }
        }
        "DeleteCard" -> {
          let msg_decoder = {
            use arg0 <- decode.field("arg0", decode.int)
            decode.success(app.DeleteCard(arg0))
          }
          case json.parse(json_str, msg_decoder) {
            Ok(msg) -> Ok(msg)
            Error(_) ->
              Error(
                "Generated Beacon message payload did not match tag DeleteCard",
              )
          }
        }
        _ -> Error("Unknown generated Beacon message tag " <> tag)
      }
    }
    Error(_) -> Error("Generated Beacon message payload missing tag")
  }
}

pub fn encode_substate_cards(state: #(app.Model, Nil, Nil)) -> String {
  let model = state.0
  json.array(model.cards, encode_board_card)
  |> json.to_string
}

pub fn substate_names() -> List(String) {
  ["cards"]
}

pub fn encode_flat_fields(state: #(app.Model, Nil, Nil)) -> String {
  let model = state.0
  json.object([
    #("next_id", json.int(model.next_id)),
    #("input", json.string(model.input)),
    #("dragging_id", json.int(model.dragging_id)),
  ])
  |> json.to_string
}
