/// AUTO-GENERATED by beacon/build — do not edit manually.
/// Re-run `gleam run -m beacon/build` to regenerate.
import beacon/element
import gleam/dynamic/decode
import gleam/json
import todo_app

fn encode_todo(s: todo_app.Todo) -> json.Json {
  json.object([
    #("id", json.int(s.id)),
    #("text", json.string(s.text)),
    #("completed", json.bool(s.completed)),
  ])
}

fn server_decode_todo() -> decode.Decoder(todo_app.Todo) {
  use id <- decode.field("id", decode.int)
  use text <- decode.field("text", decode.string)
  use completed <- decode.field("completed", decode.bool)
  decode.success(todo_app.Todo(id: id, text: text, completed: completed))
}

/// Encode the Model to JSON for model_sync.
pub fn encode_model(state: #(todo_app.Model, todo_app.Local, Nil)) -> String {
  let model = state.0
  let local = state.1
  json.object([
    #("todos", json.array(model.todos, encode_todo)),
    #("input_text", json.string(model.input_text)),
    #("next_id", json.int(model.next_id)),
    #("filter", json.string(local.filter)),
  ])
  |> json.to_string
}

/// Render the model with the same generated server contract used for SSR.
pub fn render_model(state: #(todo_app.Model, todo_app.Local, Nil)) -> String {
  let model = state.0
  let local = state.1
  todo_app.view(model, local)
  |> element.to_string
}

/// Decode a #(Model, Local, Server) from JSON string (for applying client patches).
pub fn decode_model(
  json_str: String,
) -> Result(#(todo_app.Model, todo_app.Local, Nil), String) {
  let state_decoder = {
    use todos <- decode.field("todos", decode.list(server_decode_todo()))
    use input_text <- decode.field("input_text", decode.string)
    use next_id <- decode.field("next_id", decode.int)
    use filter <- decode.field("filter", decode.string)
    decode.success(#(
      todo_app.Model(todos: todos, input_text: input_text, next_id: next_id),
      todo_app.Local(filter: filter),
      Nil,
    ))
  }
  case json.parse(json_str, state_decoder) {
    Ok(state) -> Ok(state)
    Error(_) -> Error("Failed to decode model+local+server")
  }
}

/// Decode the generated client event contract. Live event decoding never
/// renders the server view or reads the handler registry.
pub fn decode_event(
  _name: String,
  _handler_id: String,
  data: String,
  _target_path: String,
) -> Result(todo_app.Msg, String) {
  let envelope_decoder = {
    use msg_json <- decode.field("__beacon_msg", decode.string)
    decode.success(msg_json)
  }
  case json.parse(data, envelope_decoder) {
    Ok(msg_json) -> decode_msg(msg_json)
    Error(_) -> Error("Client event missing generated Beacon message envelope")
  }
}

fn decode_msg(json_str: String) -> Result(todo_app.Msg, String) {
  let tag_decoder = {
    use tag <- decode.field("tag", decode.string)
    decode.success(tag)
  }
  case json.parse(json_str, tag_decoder) {
    Ok(tag) -> {
      case tag {
        "AddTodo" -> {
          let msg_decoder = {
            decode.success(todo_app.AddTodo)
          }
          case json.parse(json_str, msg_decoder) {
            Ok(msg) -> Ok(msg)
            Error(_) ->
              Error(
                "Generated Beacon message payload did not match tag AddTodo",
              )
          }
        }
        "ToggleTodo" -> {
          let msg_decoder = {
            use arg0 <- decode.field("arg0", decode.string)
            decode.success(todo_app.ToggleTodo(arg0))
          }
          case json.parse(json_str, msg_decoder) {
            Ok(msg) -> Ok(msg)
            Error(_) ->
              Error(
                "Generated Beacon message payload did not match tag ToggleTodo",
              )
          }
        }
        "DeleteTodo" -> {
          let msg_decoder = {
            use arg0 <- decode.field("arg0", decode.string)
            decode.success(todo_app.DeleteTodo(arg0))
          }
          case json.parse(json_str, msg_decoder) {
            Ok(msg) -> Ok(msg)
            Error(_) ->
              Error(
                "Generated Beacon message payload did not match tag DeleteTodo",
              )
          }
        }
        "SetInput" -> {
          let msg_decoder = {
            use arg0 <- decode.field("arg0", decode.string)
            decode.success(todo_app.SetInput(arg0))
          }
          case json.parse(json_str, msg_decoder) {
            Ok(msg) -> Ok(msg)
            Error(_) ->
              Error(
                "Generated Beacon message payload did not match tag SetInput",
              )
          }
        }
        "SetFilter" -> {
          let msg_decoder = {
            use arg0 <- decode.field("arg0", decode.string)
            decode.success(todo_app.SetFilter(arg0))
          }
          case json.parse(json_str, msg_decoder) {
            Ok(msg) -> Ok(msg)
            Error(_) ->
              Error(
                "Generated Beacon message payload did not match tag SetFilter",
              )
          }
        }
        "ClearCompleted" -> {
          let msg_decoder = {
            decode.success(todo_app.ClearCompleted)
          }
          case json.parse(json_str, msg_decoder) {
            Ok(msg) -> Ok(msg)
            Error(_) ->
              Error(
                "Generated Beacon message payload did not match tag ClearCompleted",
              )
          }
        }
        "TodosUpdated" -> {
          let msg_decoder = {
            decode.success(todo_app.TodosUpdated)
          }
          case json.parse(json_str, msg_decoder) {
            Ok(msg) -> Ok(msg)
            Error(_) ->
              Error(
                "Generated Beacon message payload did not match tag TodosUpdated",
              )
          }
        }
        "SetTodos" -> {
          let msg_decoder = {
            use arg0 <- decode.field("arg0", decode.list(server_decode_todo()))
            decode.success(todo_app.SetTodos(arg0))
          }
          case json.parse(json_str, msg_decoder) {
            Ok(msg) -> Ok(msg)
            Error(_) ->
              Error(
                "Generated Beacon message payload did not match tag SetTodos",
              )
          }
        }
        _ -> Error("Unknown generated Beacon message tag " <> tag)
      }
    }
    Error(_) -> Error("Generated Beacon message payload missing tag")
  }
}

pub fn encode_substate_todos(
  state: #(todo_app.Model, todo_app.Local, Nil),
) -> String {
  let model = state.0
  json.array(model.todos, encode_todo)
  |> json.to_string
}

pub fn substate_names() -> List(String) {
  ["todos"]
}

pub fn encode_flat_fields(
  state: #(todo_app.Model, todo_app.Local, Nil),
) -> String {
  let model = state.0
  json.object([
    #("input_text", json.string(model.input_text)),
    #("next_id", json.int(model.next_id)),
  ])
  |> json.to_string
}
