/// AUTO-GENERATED by beacon/build — do not edit manually.
/// Re-run `gleam run -m beacon/build` to regenerate.

import chat
import beacon/element
import gleam/json
import gleam/dynamic/decode

fn encode_chatmessage(s: chat.ChatMessage) -> json.Json {
  json.object([
    #("sender", json.string(s.sender)),
    #("text", json.string(s.text)),
    #("room", json.string(s.room)),
    #("id", json.int(s.id)),
  ])
}



fn server_decode_chatmessage() -> decode.Decoder(chat.ChatMessage) {
  use sender <- decode.field("sender", decode.string)
  use text <- decode.field("text", decode.string)
  use room <- decode.field("room", decode.string)
  use id <- decode.field("id", decode.int)
  decode.success(chat.ChatMessage(sender: sender, text: text, room: room, id: id))
}



/// Encode the Model to JSON for model_sync.
pub fn encode_model(state: #(chat.Model, Nil, Nil)) -> String {
  let model = state.0
  json.object([
    #("username", json.string(model.username)),
    #("username_input", json.string(model.username_input)),
    #("has_username", json.bool(model.has_username)),
    #("current_room", json.string(model.current_room)),
    #("input_text", json.string(model.input_text)),
    #("available_rooms", json.array(model.available_rooms, json.string)),
    #("visible_messages", json.array(model.visible_messages, encode_chatmessage)),
    #("online_users", json.array(model.online_users, json.string)),
    #("session_id", json.int(model.session_id)),
    #("typing_user", json.string(model.typing_user)),
  ])
  |> json.to_string
}

/// Render the model with the same generated server contract used for SSR.
pub fn render_model(state: #(chat.Model, Nil, Nil)) -> String {
  let model = state.0
  let local = Nil
  chat.view(model, local)
  |> element.to_string
}

/// Decode a #(Model, Local, Server) from JSON string (for applying client patches).
pub fn decode_model(json_str: String) -> Result(#(chat.Model, Nil, Nil), String) {
  let state_decoder = {
    use username <- decode.field("username", decode.string)
    use username_input <- decode.field("username_input", decode.string)
    use has_username <- decode.field("has_username", decode.bool)
    use current_room <- decode.field("current_room", decode.string)
    use input_text <- decode.field("input_text", decode.string)
    use available_rooms <- decode.field("available_rooms", decode.list(decode.string))
    use visible_messages <- decode.field("visible_messages", decode.list(server_decode_chatmessage()))
    use online_users <- decode.field("online_users", decode.list(decode.string))
    use session_id <- decode.field("session_id", decode.int)
    use typing_user <- decode.field("typing_user", decode.string)

    decode.success(#(chat.Model(username: username, username_input: username_input, has_username: has_username, current_room: current_room, input_text: input_text, available_rooms: available_rooms, visible_messages: visible_messages, online_users: online_users, session_id: session_id, typing_user: typing_user), Nil, Nil))
  }
  case json.parse(json_str, state_decoder) {
    Ok(state) -> Ok(state)
    Error(_) -> Error("Failed to decode model+local+server")
  }
}

/// Decode the generated client event contract. Live event decoding never
/// renders the server view or reads the handler registry.
pub fn decode_event(_name: String, _handler_id: String, data: String, _target_path: String) -> Result(chat.Msg, String) {
  let envelope_decoder = {
    use msg_json <- decode.field("__beacon_msg", decode.string)
    decode.success(msg_json)
  }
  case json.parse(data, envelope_decoder) {
    Ok(msg_json) -> decode_msg(msg_json)
    Error(_) -> Error("Client event missing generated Beacon message envelope")
  }
}


fn decode_msg(json_str: String) -> Result(chat.Msg, String) {
  let tag_decoder = {
    use tag <- decode.field("tag", decode.string)
    decode.success(tag)
  }
  case json.parse(json_str, tag_decoder) {
    Ok(tag) -> {
      case tag {
    "UpdateInput" -> {
      let msg_decoder = {
      use arg0 <- decode.field("arg0", decode.string)
      decode.success(chat.UpdateInput(arg0))
      }
      case json.parse(json_str, msg_decoder) {
        Ok(msg) -> Ok(msg)
        Error(_) -> Error("Generated Beacon message payload did not match tag UpdateInput")
      }
    }
    "UpdateUsername" -> {
      let msg_decoder = {
      use arg0 <- decode.field("arg0", decode.string)
      decode.success(chat.UpdateUsername(arg0))
      }
      case json.parse(json_str, msg_decoder) {
        Ok(msg) -> Ok(msg)
        Error(_) -> Error("Generated Beacon message payload did not match tag UpdateUsername")
      }
    }
    "SetUsername" -> {
      let msg_decoder = {
      decode.success(chat.SetUsername)
      }
      case json.parse(json_str, msg_decoder) {
        Ok(msg) -> Ok(msg)
        Error(_) -> Error("Generated Beacon message payload did not match tag SetUsername")
      }
    }
    "SendMessage" -> {
      let msg_decoder = {
      decode.success(chat.SendMessage)
      }
      case json.parse(json_str, msg_decoder) {
        Ok(msg) -> Ok(msg)
        Error(_) -> Error("Generated Beacon message payload did not match tag SendMessage")
      }
    }
    "SwitchRoom" -> {
      let msg_decoder = {
      use arg0 <- decode.field("arg0", decode.string)
      decode.success(chat.SwitchRoom(arg0))
      }
      case json.parse(json_str, msg_decoder) {
        Ok(msg) -> Ok(msg)
        Error(_) -> Error("Generated Beacon message payload did not match tag SwitchRoom")
      }
    }
    "RoomUpdated" -> {
      let msg_decoder = {
      use arg0 <- decode.field("arg0", decode.string)
      decode.success(chat.RoomUpdated(arg0))
      }
      case json.parse(json_str, msg_decoder) {
        Ok(msg) -> Ok(msg)
        Error(_) -> Error("Generated Beacon message payload did not match tag RoomUpdated")
      }
    }
    "LoadMessages" -> {
      let msg_decoder = {
      use arg0 <- decode.field("arg0", decode.list(server_decode_chatmessage()))
      decode.success(chat.LoadMessages(arg0))
      }
      case json.parse(json_str, msg_decoder) {
        Ok(msg) -> Ok(msg)
        Error(_) -> Error("Generated Beacon message payload did not match tag LoadMessages")
      }
    }
    "ClearTypingIndicator" -> {
      let msg_decoder = {
      decode.success(chat.ClearTypingIndicator)
      }
      case json.parse(json_str, msg_decoder) {
        Ok(msg) -> Ok(msg)
        Error(_) -> Error("Generated Beacon message payload did not match tag ClearTypingIndicator")
      }
    }
        _ -> Error("Unknown generated Beacon message tag " <> tag)
      }
    }
    Error(_) -> Error("Generated Beacon message payload missing tag")
  }
}

pub fn encode_substate_visible_messages(state: #(chat.Model, Nil, Nil)) -> String {
  let model = state.0
  json.array(model.visible_messages, encode_chatmessage)
  |> json.to_string
}

pub fn substate_names() -> List(String) {
  ["visible_messages"]
}

pub fn encode_flat_fields(state: #(chat.Model, Nil, Nil)) -> String {
  let model = state.0
  json.object([
    #("username", json.string(model.username)),
    #("username_input", json.string(model.username_input)),
    #("has_username", json.bool(model.has_username)),
    #("current_room", json.string(model.current_room)),
    #("input_text", json.string(model.input_text)),
    #("available_rooms", json.array(model.available_rooms, json.string)),
    #("online_users", json.array(model.online_users, json.string)),
    #("session_id", json.int(model.session_id)),
    #("typing_user", json.string(model.typing_user)),
  ])
  |> json.to_string
}
