/// AUTO-GENERATED by beacon/build — do not edit manually.
/// Re-run `gleam run -m beacon/build` to regenerate.
import ai_chat
import beacon/element
import gleam/dynamic/decode
import gleam/json

fn encode_chatmessage(s: ai_chat.ChatMessage) -> json.Json {
  json.object([
    #("role", json.string(encode_role(s.role))),
    #("content", json.string(s.content)),
  ])
}

fn encode_role(value: ai_chat.Role) -> String {
  case value {
    ai_chat.User -> "user"
    ai_chat.Assistant -> "assistant"
  }
}

fn server_decode_chatmessage() -> decode.Decoder(ai_chat.ChatMessage) {
  use role <- decode.field("role", decode.string)
  use content <- decode.field("content", decode.string)
  decode.success(ai_chat.ChatMessage(
    role: server_decode_role_value(role),
    content: content,
  ))
}

fn server_decode_role_value(s: String) -> ai_chat.Role {
  case s {
    "user" -> ai_chat.User
    "assistant" -> ai_chat.Assistant
    _ -> ai_chat.User
  }
}

/// Encode the Model to JSON for model_sync.
pub fn encode_model(state: #(ai_chat.Model, Nil, Nil)) -> String {
  let model = state.0
  json.object([
    #("messages", json.array(model.messages, encode_chatmessage)),
    #("input_text", json.string(model.input_text)),
    #("is_streaming", json.bool(model.is_streaming)),
    #("streaming_text", json.string(model.streaming_text)),
  ])
  |> json.to_string
}

/// Render the model with the same generated server contract used for SSR.
pub fn render_model(state: #(ai_chat.Model, Nil, Nil)) -> String {
  let model = state.0
  let local = Nil
  ai_chat.view(model, local)
  |> element.to_string
}

/// Decode a #(Model, Local, Server) from JSON string (for applying client patches).
pub fn decode_model(
  json_str: String,
) -> Result(#(ai_chat.Model, Nil, Nil), String) {
  let state_decoder = {
    use messages <- decode.field(
      "messages",
      decode.list(server_decode_chatmessage()),
    )
    use input_text <- decode.field("input_text", decode.string)
    use is_streaming <- decode.field("is_streaming", decode.bool)
    use streaming_text <- decode.field("streaming_text", decode.string)

    decode.success(#(
      ai_chat.Model(
        messages: messages,
        input_text: input_text,
        is_streaming: is_streaming,
        streaming_text: streaming_text,
      ),
      Nil,
      Nil,
    ))
  }
  case json.parse(json_str, state_decoder) {
    Ok(state) -> Ok(state)
    Error(_) -> Error("Failed to decode model+local+server")
  }
}

/// Decode the generated client event contract. Live event decoding never
/// renders the server view or reads the handler registry.
pub fn decode_event(
  _name: String,
  _handler_id: String,
  data: String,
  _target_path: String,
) -> Result(ai_chat.Msg, String) {
  let envelope_decoder = {
    use msg_json <- decode.field("__beacon_msg", decode.string)
    decode.success(msg_json)
  }
  case json.parse(data, envelope_decoder) {
    Ok(msg_json) -> decode_msg(msg_json)
    Error(_) -> Error("Client event missing generated Beacon message envelope")
  }
}

fn decode_msg(json_str: String) -> Result(ai_chat.Msg, String) {
  let tag_decoder = {
    use tag <- decode.field("tag", decode.string)
    decode.success(tag)
  }
  case json.parse(json_str, tag_decoder) {
    Ok(tag) -> {
      case tag {
        "UpdateInput" -> {
          let msg_decoder = {
            use arg0 <- decode.field("arg0", decode.string)
            decode.success(ai_chat.UpdateInput(arg0))
          }
          case json.parse(json_str, msg_decoder) {
            Ok(msg) -> Ok(msg)
            Error(_) ->
              Error(
                "Generated Beacon message payload did not match tag UpdateInput",
              )
          }
        }
        "SendPrompt" -> {
          let msg_decoder = {
            decode.success(ai_chat.SendPrompt)
          }
          case json.parse(json_str, msg_decoder) {
            Ok(msg) -> Ok(msg)
            Error(_) ->
              Error(
                "Generated Beacon message payload did not match tag SendPrompt",
              )
          }
        }
        "CharDelta" -> {
          let msg_decoder = {
            use arg0 <- decode.field("arg0", decode.string)
            decode.success(ai_chat.CharDelta(arg0))
          }
          case json.parse(json_str, msg_decoder) {
            Ok(msg) -> Ok(msg)
            Error(_) ->
              Error(
                "Generated Beacon message payload did not match tag CharDelta",
              )
          }
        }
        "StreamDone" -> {
          let msg_decoder = {
            decode.success(ai_chat.StreamDone)
          }
          case json.parse(json_str, msg_decoder) {
            Ok(msg) -> Ok(msg)
            Error(_) ->
              Error(
                "Generated Beacon message payload did not match tag StreamDone",
              )
          }
        }
        "StreamError" -> {
          let msg_decoder = {
            use arg0 <- decode.field("arg0", decode.string)
            decode.success(ai_chat.StreamError(arg0))
          }
          case json.parse(json_str, msg_decoder) {
            Ok(msg) -> Ok(msg)
            Error(_) ->
              Error(
                "Generated Beacon message payload did not match tag StreamError",
              )
          }
        }
        _ -> Error("Unknown generated Beacon message tag " <> tag)
      }
    }
    Error(_) -> Error("Generated Beacon message payload missing tag")
  }
}

pub fn encode_substate_messages(state: #(ai_chat.Model, Nil, Nil)) -> String {
  let model = state.0
  json.array(model.messages, encode_chatmessage)
  |> json.to_string
}

pub fn substate_names() -> List(String) {
  ["messages"]
}

pub fn encode_flat_fields(state: #(ai_chat.Model, Nil, Nil)) -> String {
  let model = state.0
  json.object([
    #("input_text", json.string(model.input_text)),
    #("is_streaming", json.bool(model.is_streaming)),
    #("streaming_text", json.string(model.streaming_text)),
  ])
  |> json.to_string
}
